from fastapi import FastAPI, File, UploadFile, Form
from fastapi.middleware.cors import CORSMiddleware
import torch
import numpy as np
import io
from pydantic import BaseModel

app = FastAPI(title="NeuroSync API", version="1.0.0")

# Enable CORS for the React frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # For development
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class TextRequest(BaseModel):
    text: str

@app.get("/")
def read_root():
    return {"status": "NeuroSync API is running"}

@app.post("/api/embed/image")
async def embed_image(file: UploadFile = File(...)):
    # Mock behavior: In production, we pass this through ImageEncoder
    contents = await file.read()
    
    # Generate a random 512-dim embedding for demonstration
    mock_embedding = np.random.randn(512).tolist()
    
    return {
        "filename": file.filename,
        "embedding": mock_embedding,
        "modality": "image"
    }

@app.post("/api/embed/text")
async def embed_text(request: TextRequest):
    # Mock behavior: Pass text through TextEncoder
    mock_embedding = np.random.randn(512).tolist()
    return {
        "text": request.text,
        "embedding": mock_embedding,
        "modality": "text"
    }

@app.post("/api/generate")
async def generate_explanation(modality: str = Form(...), file: UploadFile = File(None)):
    # Mock behavior: Pass embedding to Phase 2 LLM Assistant
    return {
        "generated_text": "This is a mocked explanation generated by the LLM based on the multimodal embedding.",
        "confidence": 0.94
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
